version: "3.8"
services:
  nacos:
    container_name: nacos
    image: nacos/nacos-server
    network_mode: host
    volumes:
      # 添加日志目录
      - ./logs:/home/nacos/logs
    environment:
      # 环境变量 数据库连接信息
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=127.0.0.1
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=admin
      - MYSQL_SERVICE_PASSWORD=admin
    restart: always