# 配置 Promtail 监听的端口号
server:
  http_listen_port: 9080
  grpc_listen_port: 0

# 配置位置信息存储文件的路径
positions:
  filename: ./tmp/positions.yaml

# 配置 Loki 客户端
clients:
  - url: http://localhost:3100/loki/api/v1/push # 指定 Loki API 的地址
    batchsize: 1024 # 设定批量发送日志的最大数量
    batchwait: 1s # 设定批量发送的时间间隔

# 配置日志数据源
scrape_configs:
  - job_name: quick-boot-gateway # 设定 job 名称，可以任意取
    static_configs:
      - targets:
          - localhost # 设定 Promtail 在本机收集日志
        labels:
          job: quick-boot-gateway # 设定日志数据源的标签
          __path__: /var/logs/quick-boot-gateway/*.log # 设定日志文件的路径

  - job_name: quick-boot-oauth2 # 设定 job 名称
    static_configs:
      - targets:
          - localhost # 设定 Promtail 在本机收集日志
        labels:
          job: quick-boot-oauth2 # 设定日志数据源的标签
          __path__: /var/logs/quick-boot-oauth2/*.log # 设定日志文件的路径

  - job_name: quick-boot-system # 设定 job 名称
    static_configs:
      - targets:
          - localhost # 设定 Promtail 在本机收集日志
        labels:
          job: quick-boot-system # 设定日志数据源的标签
          __path__: /var/logs/quick-boot-system/*.log # 设定日志文件的路径

  - job_name: quick-boot-online # 设定 job 名称
    static_configs:
      - targets:
          - localhost # 设定 Promtail 在本机收集日志
        labels:
          job: quick-boot-online # 设定日志数据源的标签
          __path__: /var/logs/quick-boot-online/*.log # 设定日志文件的路径